-- FASE 02 — Tabelas, constraints e índices
-- Dinheiro: SEMPRE bigint em centavos (ADR-001). Percentual: basis points.
-- Invariantes de domínio (docs/produto/regras-de-dominio.md) viram
-- constraints aqui; as dinâmicas (transições, papéis) viram triggers.

-- ═══ Mesa ═══════════════════════════════════════════════════════════
create table public.tables (
  id                    uuid primary key default gen_random_uuid(),
  -- RN-001: código curto e legível, sem 0/O/1/I (I-M2)
  join_code             text not null,
  name                  text,
  status                public.table_status not null default 'ABERTA',
  settlement_mode       public.settlement_mode not null,
  -- RN-004 / I-M3: padrão 10%, em basis points (10% = 1000)
  service_fee_bp        integer not null default 1000,
  -- Recebedor (modos A/B). FK adicionada após criar participants.
  payee_participant_id  uuid,
  payee_pix_key         text,
  establishment_pix_key text,
  closing_started_at    timestamptz,
  closed_at             timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  version               bigint not null default 1,

  constraint tables_join_code_formato
    check (join_code ~ '^[2-9A-HJ-NP-Z]{6}$'),
  constraint tables_name_tamanho
    check (name is null or char_length(btrim(name)) between 1 and 60),
  constraint tables_taxa_intervalo
    check (service_fee_bp between 0 and 10000),
  -- RN-003 / I-M4: modo A exige chave PIX do recebedor desde a criação
  constraint tables_recebedor_fixo_exige_chave
    check (settlement_mode <> 'RECEBEDOR_FIXO' or payee_pix_key is not null),
  constraint tables_pix_keys_tamanho
    check (
      (payee_pix_key is null or char_length(payee_pix_key) between 1 and 140)
      and (establishment_pix_key is null
           or char_length(establishment_pix_key) between 1 and 140)
    ),
  -- Coerência estado × carimbos (máquina de estados)
  constraint tables_fechando_tem_inicio
    check (status <> 'FECHANDO' or closing_started_at is not null),
  constraint tables_fechada_tem_fim
    check (status <> 'FECHADA' or closed_at is not null)
);

create unique index tables_join_code_unico on public.tables (join_code);

-- ═══ Participante ═══════════════════════════════════════════════════
create table public.participants (
  id           uuid primary key default gen_random_uuid(),
  table_id     uuid not null references public.tables (id) on delete cascade,
  -- Identidade anônima por dispositivo (ADR-006)
  auth_user_id uuid not null references auth.users (id),
  name         text not null,
  status       public.participant_status not null default 'ATIVO',
  role         public.participant_role not null default 'MEMBRO',
  -- Ordem de entrada: desempate do maior resto (RN-042, ADR-008)
  join_order   bigint not null generated by default as identity,
  left_at      timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  version      bigint not null default 1,

  -- RN-007 / I-P1
  constraint participants_name_tamanho
    check (char_length(btrim(name)) between 1 and 30),
  -- I-P2/I-P3: quem saiu tem left_at
  constraint participants_saiu_tem_left_at
    check (status <> 'SAIU' or left_at is not null)
);

-- RN-007: nome único na mesa (case-insensitive); permanece reservado
-- mesmo após a saída (FA-05), por isso o índice não é parcial.
create unique index participants_nome_unico
  on public.participants (table_id, lower(btrim(name)));

-- I-M5: exatamente um CRIADOR ativo por mesa
create unique index participants_um_criador_ativo
  on public.participants (table_id)
  where role = 'CRIADOR' and status = 'ATIVO';

-- ADR-006: uma participação ativa por dispositivo por mesa
create unique index participants_uma_participacao_ativa
  on public.participants (table_id, auth_user_id)
  where status = 'ATIVO';

create index participants_table_idx on public.participants (table_id);
create index participants_auth_idx on public.participants (auth_user_id);

-- FK do recebedor (dependência circular resolvida aqui)
alter table public.tables
  add constraint tables_payee_fk
  foreign key (payee_participant_id) references public.participants (id);

-- ═══ Item ═══════════════════════════════════════════════════════════
create table public.items (
  id               uuid primary key default gen_random_uuid(),
  table_id         uuid not null references public.tables (id) on delete cascade,
  description      text not null,
  -- RN-020: quantidade > 0, até 3 casas (itens por peso)
  quantity         numeric(12, 3) not null,
  unit_price_cents bigint not null,
  -- total = quantidade × unitário, calculado por trigger (RN-020)
  total_cents      bigint not null,
  source           public.item_source not null default 'MANUAL',
  created_by       uuid references public.participants (id),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  version          bigint not null default 1,

  constraint items_description_tamanho
    check (char_length(btrim(description)) between 1 and 100),
  constraint items_quantity_positiva check (quantity > 0),
  constraint items_unitario_minimo check (unit_price_cents >= 1),
  constraint items_total_minimo check (total_cents >= 1)
);

create index items_table_idx on public.items (table_id);

-- ═══ Distribuição ═══════════════════════════════════════════════════
-- assignment = uma atribuição de parte de um item (RN-022/024);
-- assignment_members = quem participa dela e com que refinamento.
create table public.assignments (
  id         uuid primary key default gen_random_uuid(),
  -- desnormalizado (= item.table_id, garantido por trigger) para RLS/realtime
  table_id   uuid not null references public.tables (id) on delete cascade,
  item_id    uuid not null references public.items (id) on delete cascade,
  mode       public.assignment_mode not null,
  -- quantas unidades do item esta atribuição cobre (I-I2 via trigger)
  quantity   numeric(12, 3) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  version    bigint not null default 1,

  constraint assignments_quantity_positiva check (quantity > 0)
);

create index assignments_table_idx on public.assignments (table_id);
create index assignments_item_idx on public.assignments (item_id);

create table public.assignment_members (
  id             uuid primary key default gen_random_uuid(),
  assignment_id  uuid not null references public.assignments (id) on delete cascade,
  -- desnormalizado (= assignment.table_id, garantido por trigger)
  table_id       uuid not null references public.tables (id) on delete cascade,
  participant_id uuid not null references public.participants (id),
  -- RN-024: refinamento por quantidade (unidades) OU por peso — exatamente um
  quantity       numeric(12, 3),
  weight         integer,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  version        bigint not null default 1,

  constraint assignment_members_refinamento_unico
    check (num_nonnulls(quantity, weight) = 1),
  constraint assignment_members_quantity_positiva
    check (quantity is null or quantity > 0),
  constraint assignment_members_weight_minimo
    check (weight is null or weight >= 1),
  constraint assignment_members_participante_unico
    unique (assignment_id, participant_id)
);

create index assignment_members_table_idx on public.assignment_members (table_id);
create index assignment_members_participant_idx
  on public.assignment_members (participant_id);

-- ═══ Pagamento ══════════════════════════════════════════════════════
create table public.payments (
  id               uuid primary key default gen_random_uuid(),
  table_id         uuid not null references public.tables (id) on delete cascade,
  participant_id   uuid not null references public.participants (id),
  amount_cents     bigint not null,
  status           public.payment_status not null default 'PENDENTE',
  paid_declared_at timestamptz,
  confirmed_at     timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  version          bigint not null default 1,

  constraint payments_valor_minimo check (amount_cents >= 1),
  -- I-G2: no máximo um pagamento por participante por mesa
  constraint payments_um_por_participante unique (table_id, participant_id)
);

create index payments_table_idx on public.payments (table_id);

-- Realtime: payloads de UPDATE/DELETE completos (estrategia-realtime.md)
alter table public.tables replica identity full;
alter table public.participants replica identity full;
alter table public.items replica identity full;
alter table public.assignments replica identity full;
alter table public.assignment_members replica identity full;
alter table public.payments replica identity full;
